sudo: required
language: node_js
node_js:
- 6
services:
#- docker
#- mongodb
# addons:
#   apt:
#     sources:
#     - mongodb-3.2-precise
#     packages:
#     - mongodb-org-server
install:
 - npm install
script:
- gulp install
- gulp clean
- gulp build
- gulp lint
- gulp test
notifications:
